--add test users, roles and tasks
INSERT INTO users.users(id, authenticated, name) VALUES ( 1, TRUE,  'Engineer1');
INSERT INTO users.users(id, authenticated, name) VALUES ( 2, TRUE,  'Engineer2');
INSERT INTO users.users(id, authenticated, name) VALUES ( 3, TRUE,  'Engineer3');
INSERT INTO users.users(id, authenticated, name) VALUES ( 4, TRUE,  'Engineer4');
INSERT INTO users.users(id, authenticated, name) VALUES ( 5, TRUE,  'Engineer5');
INSERT INTO users.users(id, authenticated, name) VALUES ( 6, TRUE,  'Engineer6');
INSERT INTO users.users(id, authenticated, name) VALUES ( 7, TRUE,  'Engineer7');
INSERT INTO users.users(id, authenticated, name) VALUES ( 8, TRUE,  'Engineer8');
INSERT INTO users.users(id, authenticated, name) VALUES ( 9, TRUE,  'Engineer9');
INSERT INTO users.users(id, authenticated, name) VALUES (10, TRUE, 'Engineer10');
INSERT INTO users.users(id, authenticated, name) VALUES (11, TRUE, 'Engineer11');
INSERT INTO users.users(id, authenticated, name) VALUES (12, TRUE, 'Engineer12');
INSERT INTO users.users(id, authenticated, name) VALUES (13, TRUE, 'Engineer13');
INSERT INTO users.users(id, authenticated, name) VALUES (14, TRUE, 'Engineer14');
INSERT INTO users.users(id, authenticated, name) VALUES (15, TRUE, 'Engineer15');
INSERT INTO users.users(id, authenticated, name) VALUES (16, TRUE, 'Engineer16');
INSERT INTO users.users(id, authenticated, name) VALUES (17, TRUE, 'Engineer17');
INSERT INTO users.users(id, authenticated, name) VALUES (18, TRUE, 'Engineer18');
INSERT INTO users.users(id, authenticated, name) VALUES (19, TRUE, 'Engineer19');
INSERT INTO users.users(id, authenticated, name) VALUES (20, TRUE, 'Engineer20');
INSERT INTO users.users(id, authenticated, name) VALUES (21, TRUE, 'Engineer21');
INSERT INTO users.users(id, authenticated, name) VALUES (22, TRUE, 'Engineer22');
INSERT INTO users.users(id, authenticated, name) VALUES (23, TRUE, 'Engineer23');
INSERT INTO users.users(id, authenticated, name) VALUES (24, TRUE, 'Engineer24');
INSERT INTO users.users(id, authenticated, name) VALUES (25, TRUE, 'Engineer25');
INSERT INTO users.users(id, authenticated, name) VALUES (26, TRUE, 'Engineer26');
INSERT INTO users.users(id, authenticated, name) VALUES (27, TRUE, 'Engineer27');
INSERT INTO users.users(id, authenticated, name) VALUES (28, TRUE, 'Engineer28');
INSERT INTO users.users(id, authenticated, name) VALUES (29, TRUE, 'Engineer29');
INSERT INTO users.users(id, authenticated, name) VALUES (30, TRUE, 'Engineer30');
INSERT INTO users.users(id, authenticated, name) VALUES (31, TRUE, 'Engineer31');
INSERT INTO users.users(id, authenticated, name) VALUES (32, TRUE, 'Engineer32');
INSERT INTO users.users(id, authenticated, name) VALUES (33, TRUE, 'Engineer33');
INSERT INTO users.users(id, authenticated, name) VALUES (34, TRUE, 'Engineer34');
INSERT INTO users.users(id, authenticated, name) VALUES (35, TRUE, 'Engineer35');
INSERT INTO users.users(id, authenticated, name) VALUES (36, TRUE, 'Engineer36');
INSERT INTO users.users(id, authenticated, name) VALUES (37, TRUE, 'Engineer37');
INSERT INTO users.users(id, authenticated, name) VALUES (38, TRUE, 'Engineer38');
INSERT INTO users.users(id, authenticated, name) VALUES (39, TRUE, 'Engineer39');
INSERT INTO users.users(id, authenticated, name) VALUES (40, TRUE, 'Engineer40');
INSERT INTO users.users(id, authenticated, name) VALUES (41, TRUE, 'Engineer41');
INSERT INTO users.users(id, authenticated, name) VALUES (42, TRUE, 'Engineer42');
INSERT INTO users.users(id, authenticated, name) VALUES (43, TRUE, 'Engineer43');
INSERT INTO users.users(id, authenticated, name) VALUES (44, TRUE, 'Engineer44');
INSERT INTO users.users(id, authenticated, name) VALUES (45, TRUE, 'Engineer45');
INSERT INTO users.users(id, authenticated, name) VALUES (46, TRUE, 'Engineer46');
INSERT INTO users.users(id, authenticated, name) VALUES (47, TRUE, 'Engineer47');
INSERT INTO users.users(id, authenticated, name) VALUES (48, TRUE, 'Engineer48');
INSERT INTO users.users(id, authenticated, name) VALUES (49, TRUE, 'Engineer49');
INSERT INTO users.users(id, authenticated, name) VALUES (50, TRUE, 'Engineer50');

INSERT INTO users.roles(id, name) VALUES (1, 'public');
INSERT INTO users.roles_users(user_id, role_id) VALUES ( 1, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES ( 2, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES ( 3, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES ( 4, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES ( 5, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES ( 6, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES ( 7, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES ( 8, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES ( 9, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (10, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (11, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (12, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (13, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (14, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (15, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (16, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (17, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (18, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (19, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (20, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (21, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (22, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (23, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (24, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (25, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (26, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (27, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (28, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (29, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (30, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (31, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (32, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (33, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (34, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (35, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (36, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (37, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (38, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (39, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (40, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (41, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (42, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (43, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (44, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (45, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (46, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (47, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (48, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (49, 1);
INSERT INTO users.roles_users(user_id, role_id) VALUES (50, 1);
